version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: monthly
    time: "18:00"
    timezone: America/New York
  open-pull-requests-limit: 99
  reviewers:
  - quittle
  assignees:
  - quittle
  allow:
  - dependency-type: direct
  - dependency-type: indirect
