[package]
name = "wowser-glfw"
version = "0.0.1"
authors = ["Dustin Toff <me@dustintoff.com>"]
edition = "2018"

[dependencies]
libc = "*"
lazy_static = "*"
wowser-glfw-sys = { path = "../wowser-glfw-sys" }
wowser-macros = { path = "../wowser-macros" }
