[package]
name = "wowser-glfw"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
libc.workspace = true
lazy_static.workspace = true
wowser-glfw-sys = { path = "../wowser-glfw-sys" }
wowser-macros = { path = "../wowser-macros" }
