language: rust
services:
    - xvfb
addons:
    apt:
        packages:
            - cmake
            - libx11-dev
            - libxrandr-dev
            - libxinerama-dev
            - libxcursor-dev
            - libxi-dev
            - mesa-common-dev
            - pkg-config
            - libssl-dev
            - libgl1-mesa-dev
env:
    - RUST_BACKTRACE=1 DISPLAY=:99
before_install:
    - rustup component add rustfmt
    - rustup component add clippy
script:
    - cargo clippy --all-targets --all-features -- -D warnings
    - cargo build --all
    - cargo test --all
    - cargo fmt --all -- --check
    - cargo doc --all
