[package]
name = "wowser-glfw-sys"
version = "0.0.1"
authors = ["Dustin Toff <me@dustintoff.com>"]
edition = "2018"
links = "glfw3"

[dependencies]
wowser-gl-sys = { path = "../wowser-gl-sys" }

[build-dependencies]
cmake = "*"
git2 = "*"
bindgen = "*"
