[package]
name = "wowser-glfw-sys"
version.workspace = true
authors.workspace = true
edition.workspace = true
links = "glfw3"

[dependencies]
wowser-gl-sys = { path = "../wowser-gl-sys" }

[build-dependencies]
bindgen.workspace = true
cmake.workspace = true
git2.workspace = true
