[package]
name = "wowser-macros"
version = "0.0.1"
authors = ["Dustin Toff <me@dustintoff.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
quote = "*"
syn = "*"
