[package]
name = "wowser-gl"
version = "0.0.1"
authors = ["Dustin Toff <me@dustintoff.com>"]
edition = "2021"

[dependencies]
wowser-gl-sys = { path = "../wowser-gl-sys" }
wowser-macros = { path = "../wowser-macros" }
