[package]
name = "wowser-gl"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
wowser-gl-sys = { path = "../wowser-gl-sys" }
wowser-macros = { path = "../wowser-macros" }
