name: Rust

on:
  pull_request:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  DISPLAY: :99

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          rustup component add rustfmt
          rustup component add clippy
          sudo apt-get install \
            clang \
            cmake \
            libx11-dev \
            libxrandr-dev \
            libxinerama-dev \
            libxcursor-dev \
            libxi-dev \
            mesa-common-dev \
            pkg-config \
            libssl-dev \
            libgl1-mesa-dev \
            xvfb
      - name: Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Build
        run: cargo build --all
      - name: Test
        run: xvfb-run cargo test --all
      - name: Upload test logs on fail
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: Test logs
          path: /tmp/wowser-test
      - name: Check format
        run: cargo fmt --all -- --check
      - name: Generate Docs
        run: RUSTDOCFLAGS="-Dwarnings" cargo doc --all

  automerge:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - uses: fastify/github-action-merge-dependabot@v3.2.0 
        with:
          github-token: ${{secrets.DEPENDABOT_PAT}}
